application:
  name: cert-manager

applicationset:
  namespace: openshift-gitops

source:
  repoURL: https://github.com/WasyeaG/openshift-gox-cert-manager-workload.git
  path: charts/cert-manager

destination:
  namespace: cert-manager-operator

clusterSelector:
  key: gox.li9.com/environment

helm:
  releaseName: cert-manager
